/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mov.app_movilidad_compartida.ui;

import com.mov.app_movilidad_compartida.model.Ruta;
import com.mov.app_movilidad_compartida.model.Estudiante;
import javax.swing.DefaultListModel;
import java.util.List;

/**
 *
 * @author lusedou
 */
public class FrmPasajeroList extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPasajeroList.class.getName());
    
    private Ruta ruta;

    /**
     * Creates new form FrmPasajaeroList
     */
    public FrmPasajeroList() {
        initComponents();
    }
    
    public FrmPasajeroList(Ruta ruta) {
        this();
        this.ruta = ruta;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cargarDatos();
    }
    
    private void cargarDatos() {
        if (ruta == null) return;
        
        // Set route name
        lblFrase3.setText(ruta.getIdRuta());
        
        // Load students list
        DefaultListModel<String> model = new DefaultListModel<>();
        List<Estudiante> estudiantes = ruta.getEstudiantes();
        
        for (Estudiante e : estudiantes) {
            model.addElement(e.getNombre() + " - " + e.getCodigo() + " (" + e.getCorreo() + ")");
        }
        
        jList1.setModel(model);
        
        // Set total
        lblFrase5.setText(String.valueOf(estudiantes.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrase2 = new javax.swing.JLabel();
        lblFrase1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblFrase3 = new javax.swing.JLabel();
        lblFrase4 = new javax.swing.JLabel();
        lblFrase5 = new javax.swing.JLabel();

        lblFrase2.setFont(new java.awt.Font("Xingkai TC", 1, 24)); // NOI18N
        lblFrase2.setForeground(new java.awt.Color(0, 102, 153));
        lblFrase2.setText("RUTANAME");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFrase1.setFont(new java.awt.Font("Xingkai TC", 1, 24)); // NOI18N
        lblFrase1.setForeground(new java.awt.Color(0, 102, 153));
        lblFrase1.setText("Ruta");

        jList1.setModel(new javax.swing.DefaultListModel<>());
        jScrollPane1.setViewportView(jList1);

        lblFrase3.setFont(new java.awt.Font("Xingkai TC", 1, 24)); // NOI18N
        lblFrase3.setForeground(new java.awt.Color(0, 102, 153));
        lblFrase3.setText("RUTANAME");

        lblFrase4.setFont(new java.awt.Font("Xingkai TC", 1, 24)); // NOI18N
        lblFrase4.setForeground(new java.awt.Color(0, 102, 153));
        lblFrase4.setText("total");

        lblFrase5.setFont(new java.awt.Font("Xingkai TC", 1, 24)); // NOI18N
        lblFrase5.setForeground(new java.awt.Color(0, 102, 153));
        lblFrase5.setText("TOTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFrase1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFrase3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFrase4)
                        .addGap(18, 18, 18)
                        .addComponent(lblFrase5)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrase1)
                    .addComponent(lblFrase3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrase4)
                    .addComponent(lblFrase5))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPasajeroList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFrase1;
    private javax.swing.JLabel lblFrase2;
    private javax.swing.JLabel lblFrase3;
    private javax.swing.JLabel lblFrase4;
    private javax.swing.JLabel lblFrase5;
    // End of variables declaration//GEN-END:variables
}
